### ISSUE TITLE
首頁噗浪、Twitter 說明文字用詞問題

### ISSUE THREAD

**Issue by brlin-tw** [init-engineer/init.engineer-Android-App#13]
同一張截圖：

![Screenshot_2020-05-30-06-56-15-108_engineer kaobei](https://user-images.githubusercontent.com/13408130/83312187-127ed800-a244-11ea-926f-eeae2284d0fc.jpg)

在噗浪跟 Twitter 中似乎沒有「粉絲頁」的概念（雖然效果好像差不多），Twitter是叫做「[時間軸(timeline)](https://help.twitter.com/en/glossary#timeline)」，而噗浪則是「時間軸」跟「河道」[皆有使用](https://www.plurk.com/help/zh/timeline)（「河道」大概 UX 稍微好了點）

**Comment by Kantai235** [comment]
Thank You
