### ISSUE TITLE
看自己發過文章會閃退

### ISSUE THREAD

**Issue by dandanXO** [init-engineer/init.engineer-Android-App#8]
看自己發過文章（很早之前的）會閃退

裝置：pixel 3 xl
版本：android 10

**Comment by SmoothieNoIce** [comment]
文章id能給一下嗎

**Comment by dandanXO** [comment]
#純靠北工程師15

Id應該是這個吧

**Comment by SmoothieNoIce** [comment]
ok [1502738](https://github.com/init-engineer/init.engineer-Android-App/commit/1502738b109282230cefbe1551d2b8d4347d382f)
